# FernAssist Configuration File

# LLM Configuration (OpenAI GPT-4 with HuggingFace fallback)
llm_interpreter:
  ros__parameters:
    llm_model: "gpt-4"
    max_tokens: 200
    temperature: 0.7
    api_timeout: 30.0
    retry_attempts: 3
    enable_context_memory: true
    max_context_length: 10
    context_file_path: "/tmp/fernassist_context.json"

# AAC Listener Configuration
aac_listener:
  ros__parameters:
    confidence_threshold: 0.3
    input_timeout: 10.0
    device_polling_rate: 10.0
    enable_file_input: true
    enable_api_input: false
    enable_websocket_input: false
    enable_mock_input: true
    input_file_path: "/tmp/aac_input.txt"
    api_endpoint: "http://localhost:8080/aac/input"
    websocket_url: "ws://localhost:8080/aac/ws"

# Robot Controller Configuration
robot_controller:
  ros__parameters:
    max_velocity: 0.5
    safety_timeout: 30.0
    emergency_stop_timeout: 5.0
    movement_precision: 0.1

# System Monitor Configuration
system_monitor:
  ros__parameters:
    health_check_interval: 5.0
    component_timeout: 30.0
    log_level: "INFO"

# Safety Configuration
safety:
  ros__parameters:
    enable_emergency_stop: true
    max_obstacle_distance: 0.5
    safe_zone_radius: 2.0
    collision_detection_enabled: true 